### ISSUE TITLE
百灵试听计数出错

### ISSUE THREAD

**Issue by kdc1143** [ivanwhaf/xxqg-helper#15]
发现最近几天程序运行完后百灵试听任务的计数不增加，但是手动看百灵视频是可以完成任务的。自己做了一些尝试，没有发现是什么原因导致的。
脚本 v2.7 b3，XXQG v2.7.1

**Comment by ivanwhaf** [comment]
将vTime时间改大点，之前是16秒，现在计分时间估计改长了

**Comment by kdc1143** [comment]
我也考虑过是不是vTime不够长， 但是发现手动刷分时8~10秒切换也可以计数的，难道是XXQG加入了监测反脚本？？

**Comment by CodesHub** [comment]
可能加入了滑动速度检测，类似屏幕解锁的反模拟滑动检测。
我用root版本的`Swipe()`而不是无障碍服务的`swipe()`就行了。这两种方式主要区别是前者还可以模拟Xv，Yv信息，即输出XY运动速度信息。
当然，非root版的`swipe()`也是可以模拟出速度变化效果的，有的屏幕解锁模块实现了，好像是不断试最佳参数，具体实现没研究，希望能帮助到大佬。

**Comment by ivanwhaf** [comment]
嗯，我也发现了，新版我改成联播小视频了，用swipe模拟非线性滑动代码很烦，就直接改了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CodesHub"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月31日(星期二) 中午11:46
收件人:&nbsp;"ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送:&nbsp;"Ivan W'"<ivanwyf@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ivanwhaf/xxqg-helper] 百灵试听计数出错 (#15)




可能加入了滑动速度检测，类似屏幕解锁的反模拟滑动检测。
 我用root版本的Swipe()而不是无障碍服务的swipe()就行了。这两种方式主要区别是前者还可以模拟Xv，Yv信息，即输出XY运动速度信息。
 当然，非root版的swipe()也是可以模拟出速度变化效果的，有的屏幕解锁模块实现了，好像是不断试最佳参数，具体实现没研究，希望能帮助到大佬。
