### ISSUE TITLE
新版本有自动答题和挑战答题吗

### ISSUE THREAD

**Issue by keep-an** [ivanwhaf/xxqg-helper#16]

**Comment by ivanwhaf** [comment]
会加的



---原始邮件---
发件人: "keep-an"<notifications@github.com&gt;
发送时间: 2019年12月4日(周三) 下午5:27
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ivanwhaf/xxqg-helper] 新版本有自动答题和挑战答题吗 (#16)

**Comment by icedog111** [comment]
什么时间发新包啊

**Comment by hcy521** [comment]
群号码是多少
