### ISSUE TITLE
大侠，运行报错，最新版的能传一下吗？能加QQ群吗？

### ISSUE THREAD

**Issue by 85524365** [ivanwhaf/xxqg-helper#2]
08:57:37.005/E: illegally formed XML syntax (/storage/emulated/0/脚本/xxqg.js#1073)
illegally formed XML syntax

手机型号：华为p9
安卓版本：8.0
脚本软件：4.1

**Comment by ivanwhaf** [comment]
稍后，我这个是根据屏幕坐标来的没有做机型适配，你自己要改相应按钮的坐标位置



---原始邮件---
发件人: "85524365"<notifications@github.com&gt;
发送时间: 2019年9月5日(星期四) 上午9:03
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ivanwhaf/xxqg-helper] 大侠，运行报错，最新版的能传一下吗？能加QQ群吗？ (#2)



08:57:37.005/E: illegally formed XML syntax (/storage/emulated/0/脚本/xxqg.js#1073)
 illegally formed XML syntax
 
手机型号：华为p9
 安卓版本：8.0
 脚本软件：4.1

**Comment by 85524365** [comment]
https://github.com/sneezing/LearningPower/blob/master/main.js


目前 强国学习 程序版本是 2.51的

**Comment by ivanwhaf** [comment]
这个人写的比我好，你就用他的吧，我的没有适配，他的是获取页面元素来点击的，不需要坐标，比我高级，我之后会更新2.0




------------------ 原始邮件 ------------------
发件人: "85524365"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 上午9:28
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com>;
抄送: "Ivan W'"<874869814@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ivanwhaf/xxqg-helper] 大侠，运行报错，最新版的能传一下吗？能加QQ群吗？ (#2)




https://github.com/sneezing/LearningPower/blob/master/main.js
 
目前 强国学习 程序版本是 2.51的

**Comment by 85524365** [comment]
> 这个人写的比我好，你就用他的吧，我的没有适配，他的是获取页面元素来点击的，不需要坐标，比我高级，我之后会更新2.0
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "85524365"<notifications@github.com>; 发送时间: 2019年9月5日(星期四) 上午9:28 收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com>; 抄送: "Ivan W'"<874869814@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [ivanwhaf/xxqg-helper] 大侠，运行报错，最新版的能传一下吗？能加QQ群吗？ (#2) https://github.com/sneezing/LearningPower/blob/master/main.js 目前 强国学习 程序版本是 2.51的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ivanwhaf** [comment]
我根据那个人的重写了一个新的，根据控件来的，不像以前那样坐标了，你运行看看




------------------ 原始邮件 ------------------
发件人: "85524365"<notifications@github.com>;
发送时间: 2019年9月10日(星期二) 中午11:49
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com>;
抄送: "Ivan W'"<874869814@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ivanwhaf/xxqg-helper] 大侠，运行报错，最新版的能传一下吗？能加QQ群吗？ (#2)




Closed #2.

**Comment by 85524365** [comment]
> 我根据那个人的重写了一个新的，根据控件来的，不像以前那样坐标了，你运行看看
> […](#)

谢谢大侠，期待能看到您的新作
