### ISSUE TITLE
能不能考虑新增一个打开本地频道的功能

### ISSUE THREAD

**Issue by wuzhihui819** [ivanwhaf/xxqg-helper#30]
如题，之前新增了一个积分项。
实现很简单，只要打开过本地频道的一个功能就能实现
虽然手动也简单，但是如果能自动就更好了【手动狗头】

**Comment by ivanwhaf** [comment]
最近有时间会尽快



---原始邮件---
发件人: "wuzhihui819"<notifications@github.com&gt;
发送时间: 2020年2月9日(周日) 下午3:26
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ivanwhaf/xxqg-helper] 能不能考虑新增一个打开本地频道的功能 (#30)



如题，之前新增了一个积分项。
 实现很简单，只要打开过本地频道的一个功能就能实现
 虽然手动也简单，但是如果能自动就更好了【手动狗头】
