### ISSUE TITLE
"v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw"+         "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC"怎么得来的

### ISSUE THREAD

**Issue by keep-an** [ivanwhaf/xxqg-helper#35]

**Comment by ivanwhaf** [comment]
悬浮窗查看布局，能查看所有控件属性，不会操作可以看auto.js使用手册




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"keep-an"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月21日(星期五) 中午11:49
收件人:&nbsp;"ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ivanwhaf/xxqg-helper] "v5IOXn6lQWYTJeqX2eHuNcrPesmSud2JdogYyGnRNxujMT8RS7y43zxY4coWepspQkvw"+         "RDTJtCTsZ5JW+8sGvTRDzFnDeO+BcOEpP0Rte6f+HwcGxeN2dglWfgH8P0C7HkCMJOAAAAAElFTkSuQmCC"怎么得来的 (#35)

**Comment by keep-an** [comment]
> 悬浮窗查看布局，能查看所有控件属性，不会操作可以看auto.js使用手册

找到了，这个控件好特殊。
