### ISSUE TITLE
一个初使用者，请问如何安装使用

### ISSUE THREAD

**Issue by noway2014** [ivanwhaf/xxqg-helper#39]
已经安装auto.js，在这里看到有xxqg3.1.js.请问如何下载导入到手机auto.js里面呢？点击3.1.js看到的是代码呢

**Comment by jianyu0323** [comment]
软件右下角加号选择 导入  就能从文件看到了。然后把DB题库放到手机存储主目录  脚本 文件夹里。直接把JS脚本和DB数据库放到脚本文件夹也是可以的。放好后右边第一个三角形的符号就是运行了。你点进去看到代码 在最上面也有个运行 也是一样的

**Comment by noway2014** [comment]
谢谢楼上的回复，有个问题是，这里能下载tiku.db到手机，但是这里的xxqg_v3.1.1.js点击进入，就是代码，无法作为证件下载到手机，请问如何处理？小白感谢

**Comment by noway2014** [comment]
已经搞好
