### ISSUE TITLE
脚本导致崩溃，停止运行 xxqg_v2.1.js

### ISSUE THREAD

**Issue by kdc1143** [ivanwhaf/xxqg-helper#4]
Version: 461
Android: 27
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
android.view.InputChannel.nativeReadFromParcel(Native Method)
android.view.InputChannel.readFromParcel(Unknown Source:11)
android.view.IWindowSession$Stub$Proxy.addToDisplay(Unknown Source:96)
android.view.ViewRootImpl.setView(Unknown Source:450)
android.view.WindowManagerGlobal.addView(Unknown Source:243)
android.view.WindowManagerImpl.addView(Unknown Source:15)
android.widget.Toast$TN.handleShow(Unknown Source:189)
android.widget.Toast$TN$1.handleMessage(Unknown Source:13)
android.os.Handler.dispatchMessage(Unknown Source:21)
android.os.Looper.loop(Unknown Source:145)
android.app.ActivityThread.main(Unknown Source:67)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
com.android.internal.os.ZygoteInit.main(Unknown Source:339)
de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by ivanwhaf** [comment]
是一开始运行就报错，还是运行到哪一步报错？我看报错描述是兼容性问题，我autojs版本是4.0能完美运行



---原始邮件---
发件人: "kdc1143"<notifications@github.com&gt;
发送时间: 2019年9月27日(星期五) 上午8:56
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ivanwhaf/xxqg-helper] 脚本导致崩溃，停止运行 (#4)



Version: 461
 Android: 27
 java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
 android.view.InputChannel.nativeReadFromParcel(Native Method)
 android.view.InputChannel.readFromParcel(Unknown Source:11)
 android.view.IWindowSession$Stub$Proxy.addToDisplay(Unknown Source:96)
 android.view.ViewRootImpl.setView(Unknown Source:450)
 android.view.WindowManagerGlobal.addView(Unknown Source:243)
 android.view.WindowManagerImpl.addView(Unknown Source:15)
 android.widget.Toast$TN.handleShow(Unknown Source:189)
 android.widget.Toast$TN$1.handleMessage(Unknown Source:13)
 android.os.Handler.dispatchMessage(Unknown Source:21)
 android.os.Looper.loop(Unknown Source:145)
 android.app.ActivityThread.main(Unknown Source:67)
 java.lang.reflect.Method.invoke(Native Method)
 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
 com.android.internal.os.ZygoteInit.main(Unknown Source:339)
 de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by kdc1143** [comment]
更新到2.2，已经没问题了，多谢！！！
