### ISSUE TITLE
建议转发分享后加一个判断语句

### ISSUE THREAD

**Issue by 85524365** [ivanwhaf/xxqg-helper#5]
建议转发分享后加一个判断语句，如果没回到学习强国页面，则继续后退一步。这样即使微信没有登录也可以转发分享。

**Comment by ivanwhaf** [comment]
你的意思是没登录的话退回会回到微信主页么



---原始邮件---
发件人: "85524365"<notifications@github.com&gt;
发送时间: 2019年10月3日(星期四) 晚上10:42
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [ivanwhaf/xxqg-helper] 建议转发分享后加一个判断语句 (#5)



建议转发分享后加一个判断语句，如果没回到学习强国页面，则继续后退一步。这样即使微信没有登录也可以转发分享。

**Comment by 85524365** [comment]
是的，大神，如果微信没有登陆，返回是不成功的，需要手工点一下返回，才能继续运行下去。
建议加一个判断语句如果没回到学习强国界面，就back一下。

**Comment by ivanwhaf** [comment]
好的，谢谢建议，我拿我手机试试



---原始邮件---
发件人: "85524365"<notifications@github.com&gt;
发送时间: 2019年10月3日(星期四) 晚上11:46
收件人: "ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Ivan"<874869814@qq.com&gt;;
主题: Re: [ivanwhaf/xxqg-helper] 建议转发分享后加一个判断语句 (#5)



是的，大神，如果微信没有登陆，返回是不成功的，需要手工点一下返回，才能继续运行下去。
 建议加一个判断语句如果没回到学习强国界面，就back一下。
