### ISSUE TITLE
建议设置一个随机时间，看文章跟视频不要精确到刚好看完就看下一条

### ISSUE THREAD

**Issue by auslin45** [ivanwhaf/xxqg-helper#57]
太精确了很容易被监控到吧，弄个随机时间，每条文章跟视频看完后再看一个随机时间，大数据看到你每条文章跟视频时间一到就下一条很容易就判断是机器学习了，还有之前的“徐特立”，后台一查到答案答“徐特立“的可以直接封了T_T

**Comment by ivanwhaf** [comment]
自行在文章时间那儿加一个随机函数random即可，下次更新会加上去


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AusLin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 上午8:49
收件人:&nbsp;"ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ivanwhaf/xxqg-helper] 建议设置一个随机时间，看文章跟视频不要精确到刚好看完就看下一条 (#57)





 
太精确了很容易被监控到吧，大数据看到你每条文章跟视频时间一到就下一条很容易就判断是机器学习了，还有之前的“徐特立”，后台一查到答案答“徐特立“的可以直接封了T_T

**Comment by smiletianque** [comment]
> 自行在文章时间那儿加一个随机函数随机，立即，下次更新会加上去
> […](#)
> ------------------＆nbsp;原始邮件＆nbsp; ------------------发件人：“ AusLin “ <notifications@github.com> ;; 发送时间：＆nbsp; 2020年4月27日（星期一）上午8:49收件人：＆quot; ivanwhaf / xxqg-helper“ <xxqg-helper@noreply.github.com> ;; 抄送：“ Subscribed” <subscribed@noreply.github.com> ;; 主题：[ivanwhaf / xxqg-helper]建议设置一个随机时间，看文章跟视频不要精确到刚好看完就看下一条（[＃57](https://github.com/ivanwhaf/xxqg-helper/issues/57)）太精确了很容易被监控到吧，大数据看到你每条文章跟视频时间一到就下一条很容易就判断是机器学习了，还有之前的“徐特立”，后台一查到答案答“徐特立”的可以直接封了T_T-收到此消息是因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

最好答题那，也做个随机延时函数。多谢大佬

**Comment by adamnb1** [comment]
大佬，最新题库是哪个？能不能发个全点的题库。

**Comment by ivanwhaf** [comment]
没有最新的，代码里只有根据每日答题更新题库，不能手动添加，要新的请移步别的助手


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"adamnb1"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月9日(星期六) 中午11:19
收件人:&nbsp;"ivanwhaf/xxqg-helper"<xxqg-helper@noreply.github.com&gt;;
抄送:&nbsp;"ivan"<ivanwyf@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ivanwhaf/xxqg-helper] 建议设置一个随机时间，看文章跟视频不要精确到刚好看完就看下一条 (#57)





 
大佬，最新题库是哪个？能不能发个全点的题库。
