### ISSUE TITLE
有没有大神可以获取到学习推荐文章页面的每个文章的标题

### ISSUE THREAD

**Issue by wanghuisenior** [ivanwhaf/xxqg-helper#73]
`var currentNewsTitle=""
        	if (textContains("来源").exists()) { // 有时无法获取到 来源
        		currentNewsTitle=descContains("来源").findOne().parent().children()[0].desc();
        	}else if (textContains("作者").exists()){
        		currentNewsTitle=descContains("作者").findOne().parent().children()[0].desc();
        	}`
原来我是这么获取的，把已经学过的文章标题放到数据库里，下次不学他了，现在软件更新后怎么获取呢，感谢，还有，我还不知道怎么调出可以看到app控件呢

**Comment by wanghuisenior** [comment]
已解决，可以去看我主页，Android5完美运行，Android10待更新

**Comment by lolisaikou** [comment]
![image](https://user-images.githubusercontent.com/32028165/84973813-8da52100-b154-11ea-81e8-a96ebcf84aab.png)
安卓10可以这样获取

**Comment by bxtww** [comment]
let currentNewsTitle = ""
        if (text(date_string).findOnce(t) != null) {
            currentNewsTitle = text(date_string).findOnce(t).parent().parent().parent().child(0).text();
        }

**Comment by xiaodiaoz** [comment]
function dad(){
    // 创建或打开一个数据库文件，在当前目录的db文件
    let db = sqlite.open("./tiku.db", {version: 1}, {
    });
    var a = className("android.view.View").depth(21).findOnce(0).desc()//日期
    var b = className("android.view.View").depth(21).findOnce(1).desc()//新闻标题

    db.insert("dad", {
        day: a,
        news: b,
    
    });
} 
7.0可用  4.0不知道为啥我调用java的函数，sqlite.open换成原脚本里的就报错。。

**Comment by wanghuisenior** [comment]
> function dad(){
> // 创建或打开一个数据库文件，在当前目录的db文件
> let db = sqlite.open("./tiku.db", {version: 1}, {
> });
> var a = className("android.view.View").depth(21).findOnce(0).desc()//日期
> var b = className("android.view.View").depth(21).findOnce(1).desc()//新闻标题
> 
> ```
> db.insert("dad", {
>     day: a,
>     news: b,
> 
> });
> ```
> 
> }
> 7.0可用 4.0不知道为啥我调用java的函数，sqlite.open换成原脚本里的就报错。。

var db = SQLiteDatabase.openOrCreateDatabase(path, null);

**Comment by zxcvbnm3111** [comment]
这些代码怎么合在一起

**Comment by zxcvbnm3111** [comment]
还有就是已经记录的文章点进去会退出吗

**Comment by xiaodiaoz** [comment]
> function dad(){
> // 创建或打开一个数据库文件，在当前目录的db文件
> let db = sqlite.open("./tiku.db", {version: 1}, {
> });
> var a = className("android.view.View").depth(21).findOnce(0).desc()//日期
> var b = className("android.view.View").depth(21).findOnce(1).desc()//新闻标题
> 
> ```
> db.insert("dad", {
>     day: a,
>     news: b,
> 
> });
> ```
> 
> }
> 7.0可用 4.0不知道为啥我调用java的函数，sqlite.open换成原脚本里的就报错。。

我当时就是这样写的，还是报错，不知道哪里错了
