### ISSUE TITLE
错误：illegally formed XML syntax（/storage/emulated/0/脚本/xxqg _v3.1.3.js#11156)

### ISSUE THREAD

**Issue by jiajing73** [ivanwhaf/xxqg-helper#74]
手机是小米mix3，系统是MIUI 11.0.3稳定版。求帮助解决，不胜感激！

**Comment by lolisaikou** [comment]
先确认一下js里代码是否完整，或者是否可读。
这代码一共才1300行，那个报错都到1万行了

**Comment by jiajing73** [comment]
就是在这里下的脚本啊，试了很多次都不行

**Comment by lolisaikou** [comment]
复制[这里](https://tibiji.com/share/IcIBiGbJHJ)的文本到替换一下试试
